spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: -
    username: -

  h2:
    console:
      enabled: true
