spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: ture
    defer-datasource-initialization: true
  datasource:
    url: -
    username: -

  h2:
    console:
      enabled: true
#  sql:
#    init:
#      data-locations: import.sql


jwt:
  issuer: ajufresh@gmai.com
  secret: studySpringbootBase64NeedToSizeMoreThan256Bite

