spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: ture
    defer-datasource-initialization: true
  datasource:
    url: -
    username: -

  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: d
            client-secret: d
          scope:
            - email
            - profile
#  sql:
#    init:
#      data-locations: import.sql


jwt:
  issuer: ajufresh@gmai.com
  secret: studySpringbootBase64NeedToSizeMoreThan256Bite

